name: "Install and Cache Node Modules"
description: "My first Composite Action"
runs:
  # указываем тип action'а
  using: composite
  steps:
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-file-
            ${{ runner.os }}-

      - name: Show cache files
        shell: bash
        run: echo ${{ toJson(steps.cache-node-modules.outputs) }}

      - name: Install dependecies
        shell: bash
        run: npm install