name: 05-workflow

on:
  - push
  - issues
  - pull_request

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Events Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
