name: 06_workflow

on:
  # Событие push сработает только при пуше изменений в ветку main по тегу v1
  push:
    branches:
      - main
      - "feature-*" # выбор любой ветки, имя которой начинается с feature
      - "!feature-01" # исключить указанную ветку из выбора
    # tags:
    #   - "v1.*" # паттерн, который соответствует любому из вариантов - v1.1, v1.2, v1.2.3 и тд
    #   - "!v1.2.3" # при помощи знака ! исключается указанная версия тега
    paths:
      - "**.html" # отслеживать изменения только в файлах с расширением html

jobs:
  primo_job:
    runs-on: ubuntu-latest
    steps:
      - name: first-job
        run: node -v
