name: 08_workflow

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        required: true
        default: "Just some title"
        description: "Awesome title"

jobs:
  primo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Primo step
        run: |
          echo "Here is title ${{ inputs.title }}"
