name: 08_workflow

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        required: true
        default: "Just some title"
        description: "Awesome title"
      select:
        type: choice
        required: true
        description: "Select some value"
        options:
          - value 1
          - value 2
          - value 3
          - value 4
        default: "value 2"
      check:
        type: boolean
        required: false
        description: "Check state"

jobs:
  primo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Primo step
        run: |
          echo "Here's title: ${{ inputs.title }}"
          echo "Here's select: ${{ inputs.select }}"
          echo "Here's checkbox: ${{ inputs.check }}"
