name: 11_workflow

run-name: Variables

env:
  WF_CUSTOM_VAR: "global variable" # переменная, доступная во всем конкретном workflow

on:
  - push

jobs:
  primo_job:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: "job variable" # переменная, доступная внутри конкретной job
    steps:
      - name: primo step
        env:
          STEP_CUSTOM_VAR: "step variable" # переменная уровня конкретного step
          WF_CUSTOM_VAR: "global variable modified" # изменяем значение глобальной переменной
        run: |
          echo $GITHUB_REF
          echo ${{ github.ref }}
          echo $WF_CUSTOM_VAR
          echo ${{ env.WF_CUSTOM_VAR }}
          echo $JOB_CUSTOM_VAR
          echo $STEP_CUSTOM_VAR
