name: Variables and Secrets
run-name: "Variables and Secrets"
on:
  - push

jobs:
  primo_job:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Show secrets and variables
        run: |
          echo ${{ vars.STATUS }}
          echo ${{ secrets.PASSWORD }}
