name: Status Functions
run-name: "Status Functions"
on:
  - push

jobs:
  primo_job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        # run: sleep 30
        run: exit 1
      - name: Run on Cancelled # Если cancelled() вернет true, данный шаг выполнится
        if: ${{ cancelled() }}
        run: echo "Run on Cancelled"
      - name: Run on Success # Данный шаг выполнится при успехе
        if: ${{ success() }}
        run: echo "Run on Success"
      - name: Run on any case # Шаг запустится в любом случае
        if: ${{ always() }}
        run: echo "Run on any case"
      - name: Run on Failure # Данный шаг выполнится только в том случае, если один из предыдущих шаг завершится с ошибкой
        if: ${{ failure() }}
        run: echo "Run on Failure"
  secondo_job:
    runs-on: ubuntu-latest
    # Зависит от джобы primo_job
    needs: primo_job
    # Проверяем, что первая джоба завершилась с неудачей
    if: ${{ failure() }}
    steps:
      - name: Run if first job failed
        run: echo "I\m successful job!"
