name: Matrix Workflow

run-name: Matrix Workflow

on: workflow_dispatch

jobs:
  matrix_job:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16, 18, 20]
      fail-fast: true
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      # step 1
      - run: node -v
      # step 2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # step 3
      - run: node -v
