# workflow, который вызывает на исполнение другой workflow
name: Reuse Template Workflow

run-name: Reuse Template Workflow

on:
  # вызываем workflow вручную
  workflow_dispatch:
    # эти данные будем передавать в вызываемый workflow
    inputs:
      title:
        description: "Test title"
        type: string
        default: "Default title"
        required: true

jobs:
  # workflow в текущем репозитории
  call-workflow:
    # указываем путь к workflow, который будем вызывать на исполнение
    uses: ./.github/workflows/17_callable-template.workflow.yml
    # указываем, что будем передавать в вызываемый workflow
    with:
      title: "${{ inputs.title }}"
  # отображаем переменную из вызываемого workflow
  # то есть - можем обратиться к переменной, доступной извне в другом workflow
  show_output_variable:
    # нужно дождаться (needs) выполнения workflow ./.github/workflows/17_callable-template.workflow.yml
    # и выполнить шаг в отдельном процессе - поэтому нужен новый runner (runs-on)
    runs-on: ubuntu-latest
    needs:
      - call-workflow
    steps:
      - name: Show output variable
        # обращаемся к контексту needs и по цепочке обращаемся к переменной во внешнем workflow
        run: echo "${{ needs.call-workflow.outputs.current_date }}"
  # workflow в стороннем репозитории
  external-workflow:
    # ссылка на полный путь к репозиторию с вызываемым workflow
    uses: gearDocker/githib_actions_workflows/.github/workflows/callable.workflow.yml@main
    # указываем, что будем передавать в вызываемый workflow
    secrets:
      PASSWORD: "${{ secrets.PASSWORD }}"
