name: Reuse Template Workflow

run-name: Reuse Template Workflow

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Test title"
        type: string
        default: "Default title"
        required: true

jobs:
  call-workflow:
    # указываем путь к тому workflow, который будем вызывать на исполнение
    uses: ./.github/workflows/17_callable-template.workflow.yml
    with:
      title: "${{ inputs.title }}"
  ext-workflow:
    uses: gearDocker/githib_actions_workflows/.github/workflows/callable.workflow.yml@main
    secrets:
      PASSWORD: "${{ secrets.PASSWORD }}"
