name: Docker Workflow

run-name: Docker Workflow

on:
  # вызываем workflow вручную
  workflow_dispatch

jobs:
  run_docker:
    runs-on: ubuntu-latest
    # Используем docker-сервисы
    services:
      # конкретный docker-сервис и его image
      postgres:
        image: postgres:17.4
    # здесь указываем, что будем использовать конкретный docker-образ
    container:
      image: node:18-alpine
    # шаги выполняем уже в среде docker-образа, не текущего runner'а
    steps:
      - name: Show Node version
        run: node -v
      - name: Show service
        run: echo "${{ toJson(job.services.postgres) }}"
