name: Using Composite Action Workflow
run-name: Using Composite Action Workflow
on: workflow_dispatch

jobs:
  test_composite_action:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Using custom action
        # путь к кастомному action
        uses: ./.github/actions/cache-node-module
        # передаем дополнительный параметр в кастомный action
        with:
          caching: "false"
