name: Fourth Workflow

on:
  # Указываем workflow, от выполнения которых зависит выполнение данного workflow
  workflow_run:
    # Массив workflows, от которых зависит выполнение данного workflow
    workflows:
      - Third Workflow
    # Тип состояния workflows, от которых зависит выполнение данного workflow
    # в данном случае говорим, что текущий workflow запустится после завершения (completed) указанных выше workflows
    types:
      - completed

jobs:
  success_job:
    runs-on: ubuntu-latest
    # проверяем статус выполнения workflow, указанного как зависимость
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Job Success
        run: echo "Success job"
  failure_job:
    runs-on: ubuntu-latest
    # проверяем статус выполнения workflow, указанного как зависимость
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Job Failure
        run: echo "Failure job"
