name: Second Workflow

on:
  - push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Node info
        run: node -v
  second_job:
    runs-on: macos-latest
    steps:
      - name: Display Node info
        run: node -v
  third_job:
    runs-on: windows-latest
    needs:
      - first_job
      - second_job
    steps:
      - name: Display Node info
        run: node -v
