name: Third Workflow

on:
  - push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show working directory before
        run: ls -a
      - uses: actions/checkout@v4
      - name: Show working directory after
        run: ls -a
